"""Add proxies table

Revision ID: bebcfd2c8ea8
Revises: f837cc3ec81f
Create Date: 2018-01-04 11:41:06.397631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebcfd2c8ea8'
down_revision = 'f837cc3ec81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('port', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxies')
    # ### end Alembic commands ###
