"""Scrape Count and Date

Revision ID: f5a8f70f3c55
Revises: fc117a189b67
Create Date: 2018-01-18 17:36:42.467650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a8f70f3c55'
down_revision = 'fc117a189b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proxies', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('start_urls', sa.Column('scrape_count', sa.Integer(), nullable=True))
    op.add_column('start_urls', sa.Column('scrape_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('start_urls', 'scrape_date')
    op.drop_column('start_urls', 'scrape_count')
    op.alter_column('proxies', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
