"""Add usage_count to proxies table

Revision ID: fc117a189b67
Revises: bebcfd2c8ea8
Create Date: 2018-01-04 14:20:12.194077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc117a189b67'
down_revision = 'bebcfd2c8ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('usage_count', sa.Integer(),
                                       nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'usage_count')
    # ### end Alembic commands ###
